#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z=1) in;
layout (binding = 0, rgba8) uniform readonly imageCube inputImage;
layout (binding = 1, rgba8) uniform imageCube resultImage;

#include "../glsl/sampling.glsl"
#include "../glsl/random.glsl"
#include "../glsl/cubemap.glsl"
#include "../glsl/hdr.glsl"

void main()
{
    vec4 rgbe = imageLoad(inputImage, ivec3(gl_GlobalInvocationID.xyz));

    imageStore(resultImage, ivec3(gl_GlobalInvocationID.xyz), rgbe);
}